### ISSUE TITLE
Line 47 of app/public/bower/breakpoint-sass/_breakpoint.scss: Invalid CSS after "...ntext holder') ": expected "}", was "!global;"

### ISSUE THREAD

**Issue by spenoir** [at-import/breakpoint#104]
Why am I getting this error? 

line 47 looks like this:

```
$private-breakpoint-context-holder: map-get($breakpoint, 'context holder') !global;
```

full stack trace has been concatenated I'm afraid. might be able to get something. Is !global valid?

**Comment by patriksima** [comment]
Hello, I got same error. sass -v => Sass 3.4.19 (Selective Steve)

**Comment by patriksima** [comment]
I figured it out. I guess it just remove ruby-sass package. Apparently it conflicts with gem-sass
