### ISSUE TITLE
Query return without first argument

### ISSUE THREAD

**Issue by ockam** [at-import/breakpoint#121]
When writing `@include breakpoint(800px)`, breakpoint returns `@media  and (min-width: 800px)`

I presume this may be a compiler issue, because I have used Breakpoint in another project where I was compiling with Codekit (and it worked). This time I’m compiling with Gulp (gulp-sass).

I have Sass 3.3.4 installed.

Thoughts?

**Comment by alexluke** [comment]
Setting `$breakpoint-force-media-all: true` seems to get around this issue for now.

**Comment by ockam** [comment]
Don’t know if I found another bug but I tried @alexluke solution and it only work on the first declaration; all remaining declaration are still empty.

**Comment by Snugug** [comment]
Libsass 3.1 is still not fully compatible with Sass 3.4, but it's getting close. I've run some manual tests and Breakpoint is mostly working with 3.1, but there are still some edge cases where it doesn't. We are taking the position that we will not rewrite portions of Breakpoint to work around Libsass incompatibilities as it is on track to be feature compatible and moving forward will be kept up-to-date.

That all being said, this issue appears to be resolved using Libsass 3.1. If you can confirm that to be the case, I'd love to close this.

**Comment by ockam** [comment]
I’m running gulp-sass 1.3.1 which use node-sass 2.0.0-beta which use libsass 3.1.0-beta and the problem is not solved. Tried with and without "force all media type".

**Comment by Snugug** [comment]
Try it w/o the beta.

**Comment by gregtillbrook** [comment]
I just found my way here as I had the same issue but upgrading to latest grunt-sass (v0.18.1 as of writing this) fixed the problem for me.

I'd say this issue can be closed now.

**Comment by lolmaus** [comment]
So what is the current status? Can Breakpoint be run on libsass without any worries?

**Comment by ockam** [comment]
Yes, if you use the latest version of libsass.

**Comment by aderaaij** [comment]
Yes, no problem with the latest version of Libsass

**Comment by rockitdev** [comment]
For me, running libsass 3.2.2, i still have this issue. adding 

    $breakpoint-force-media-all: true;

provides a solution. I notice that on SassMeister, this isn't a problem, so it is likely an issue with my system config.
