### ISSUE TITLE
breakpoint-to-ems - base font size?

### ISSUE THREAD

**Issue by welly** [at-import/breakpoint#122]
Hello,

Firstly, great library - thanks very much for building and supporting it! My question is regarding the $breakpoint-to-ems variable. My preference is to use ems for layouts and so have this enabled. Where does breakpoint get the base font size to calculate the em value from? It appears by default it is using 16px. Can this be changed anywhere and if so, where?

Thanks!

**Comment by welly** [comment]
Update: I found what should be the value that sets the base font size in _breakpoint.scss. However, changing the value does not appear to work.

Using the default value:

```
.test {
  color: green;

  @include breakpoint(320px) {
    color: blue;
  }

  @include breakpoint(768px) {
    color: red;
  }
}
```

This resulted in the following:

```
.test {
  color: green;
}
@media (min-width: 20em) {
  .test {
    color: blue;
  }
}
@media (min-width: 48em) {
  .test {
    color: red;
  }
}
```

I created a $breakpoint-base-font-size value which I set to 10px and recompiled my sass file. Same results:

```
.test {
  color: green;
}
@media (min-width: 20em) {
  .test {
    color: blue;
  }
}
@media (min-width: 48em) {
  .test {
    color: red;
  }
}
```

Not sure this is quite correct? Or is it? I would have expected min-width: 32em and min-width: 76.8em.

Any thoughts?

Thanks!

**Comment by Snugug** [comment]
Media query `em` conversion is not based on the document's root font size, but rather the *de facto* standard conversion of `1em / 16px` that is true across all browsers. As such, we don't allow users to change this ratio when using `em` based media queries. The `em`s aren't document `em`s, they are browser `em`s.

**Comment by welly** [comment]
Gotcha. I can work with that!

Cheers
