### ISSUE TITLE
`Error: unterminated interpolant` using gulp-sass

### ISSUE THREAD

**Issue by FStop** [at-import/breakpoint#123]
Using gulp-sass I get the following error:
```
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: unterminated interpolant inside string constant '#{breakpoint-get('
```

So close to being able to use Libsass! This is probably because gulp-sass uses node-sass, which is probably not at the latest version of Libsass, right? Can't wait for everything to catch up.

**Comment by Snugug** [comment]
Please 2x check that you are using the latest version of `node-sass`. The current version which uses 3.1 doesn't throw this error when running our test suite.

**Comment by FStop** [comment]
`npm-list` shows gulp-sass@1.3.2 is using node-sass@2.0.0-beta, which is listed as the latest release: https://www.npmjs.com/package/node-sass.

**Comment by Snugug** [comment]
That's what I've used to test as well. Can you pair down the Sass you're using to determine the source of the error?

**Comment by FStop** [comment]
I pared it down to nothing but `@import 'breakpoint';` and was still getting the error. So I searched the breakpoint files for the string it was barfing on, `#{breakpoint-get(`, and found it in [one place](https://github.com/at-import/breakpoint/blob/2.x.x/stylesheets/breakpoint/_helpers.scss#L15). I commented out that line, and the error seems to be gone.

I don't know why, but maybe you've got ideas on that.

**Comment by Snugug** [comment]
Haha! I know why it's not broken in my test suite! Because I fixed that but haven't committed it back upstream yet! Doh! I should do that.

**Comment by Snugug** [comment]
How are you including Breakpoint? Are you using a tag or are you using `master`? It just occurred to me that the code you're pointing to hasn't officially been released yet.

**Comment by FStop** [comment]
I included Breakpoint by downloading the zip from the main repo page and including the Sass files. Now I see that it defaults to `2.x.x`, so yeah, I guess I'm not using `master`.

**Comment by Snugug** [comment]
That's master for this major version, but it's not all released code. Try the zip of one of the releases

**Comment by FStop** [comment]
That would make sense, though, and I'm not very well known for that.

In any case I've backed away from LibSass for now. It sill has some lingering little bugs that I don't have time to work around.
