### ISSUE TITLE
error

### ISSUE THREAD

**Issue by simondegheselle** [at-import/breakpoint#124]
I tried to use breakpoint but i came across this error, any suggestions on how to fix this?

[Error: error plugins/breakpoint/breakpoint/parsers/_triple.scss (Line 32: List index is 2 but list is only 1 item long for `nth')]
  message: 'error plugins/breakpoint/breakpoint/parsers/_triple.scss (Line 32: List index is 2 but list is only 1 item long for `nth\')',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-ruby-sass',
  __safety: { toString: [Function] } }

**Comment by Snugug** [comment]
Please provide a reduced example demonstrating the error on http://sassmeister.com/

**Comment by simondegheselle** [comment]
Ohh my bad, i misused max-width, that's why it passed 2 elements through

@include breakpoint(max-width 1000px) {
         @include span(6);             
}

**Comment by Snugug** [comment]
Does this mean that I can close this?

**Comment by simondegheselle** [comment]
yes thanks
