### ISSUE TITLE
NPM Support?

### ISSUE THREAD

**Issue by rsumilang** [at-import/breakpoint#129]
Would you guys consider adding npm support? I think all this requires is a package.json file.

**Comment by Snugug** [comment]
Npm support will come in the form of an eyeglass module and is in the pipeline.

https://github.com/sass-eyeglass/eyeglass

**Comment by elektronik2k5** [comment]
@Snugug can you please elaborate? Should I wait a bit for eyeglass as you suggested or create a pull request with a package.json?
Thank you!

**Comment by Snugug** [comment]
Waiting for Eyeglass

**Comment by obweger** [comment]
+1 for @elektronik2k5's PR. Full support for eyeglass, but NPM is 100% valuable also without it.
