### ISSUE TITLE
Incompatible unit

### ISSUE THREAD

**Issue by davids701124** [at-import/breakpoint#130]
I set a variable 500px. The error occur and says the px is incompatible unit. So I remove px, then it returns me the em doesn't make sense.

@media (min-width: 2716.25em) {
  /* line 43, sass/style.scss */
  header {
    content: 'Basic Media Query';
  }
  /* line 126, bower_components/breakpoint/breakpoint/_core.scss */
  header .wrapper {
    width: 2713.75em;
  }
}
@media (min-width: 4.12154em) {
  /* line 43, sass/style.scss */
  header {
    content: 'Paired Media Query';
  }
  /* line 126, bower_components/breakpoint/breakpoint/_core.scss */
  header .wrapper {
    width: 1.62154em;
  }
}

**Comment by Snugug** [comment]
Please provide a reduces use case showing this behavior on http://sassmeister.com/ using the correct version of Sass and Breakpoint you are using.

**Comment by davids701124** [comment]
`header{
	width: 84%;
  margin: 0 auto;
	@include breakpoint(500) {
    // Some style
  }
	
	.logo{
		float: left;
		position: relative;
  	left: 3.333333%;
  	z-index: 100;
	}
	
	nav{	
		float: right;
		top: 90px;
  	position: relative;

		a{
			font-family: 'Droid Serif', serif;
			text-transform: uppercase;
			font-size: 1.1em;
		}
	}
}

**Comment by Snugug** [comment]
No movement, closing
