### ISSUE TITLE
Bower version 2.5.0?

### ISSUE THREAD

**Issue by a1russell** [at-import/breakpoint#135]
Currently the version in `bower.json` is listed as 2.4.2, but it is 2.5.0 according to `breakpoint.rb`. ~~Should the version in `bower.json` be updated to 2.5.0?~~ Since bower uses Git tags for versioning, please remove the version property from `bower.json` to eliminate any confusion or redundant information.

*Edited to reflect suggestion from @williamboman below.*

**Comment by williamboman** [comment]
The `version` property in `bower.json` is not used by bower at all. Bower is, as of now, entirely git-based, where a bower package's versions are its git tags (the tags that are semver-compliant). If anything - the version property should be removed from `bower.json`.

**Comment by Snugug** [comment]
New version being published today
