### ISSUE TITLE
Bower: compass-breakpoint instead of breakpoint-sass

### ISSUE THREAD

**Issue by pepelsbey** [at-import/breakpoint#143]
So when I install it via `bower i breakpoint-sass` I get it inside of `bower_components/compass-breakpoint` folder instead of expected `breakpoint-sass`.
```
{
  "name": "compass-breakpoint",
  "version": "2.6.1",
  "main": "stylesheets/_breakpoint.scss",
…
```
Is there a reason for that?

**Comment by apansky** [comment]
same here, its working, but its bugging me.. any explanation?

**Comment by zhawkins** [comment]
If you install singularity with bower which installs breakpoint, it names the directory 'breakpoint-sass'. If breakpoint is installed by itself with bower it names the directory 'compass-breakpoint'. Not sure why, I imagine something to do with the bower.json name, but you can work around it with:
```
bower install breakpoint-sass=breakpoint-sass
```
From the [bower api](http://bower.io/docs/api/#install):
```
<name>=<package>#<version>
```

**Comment by alekspetrov** [comment]
@zhawkins it works for me. Thanks for share.

**Comment by AdamGerthel** [comment]
Agreed, this is weird. Am using @zhawkins workaround for the moment.
