### ISSUE TITLE
Breakpoint 2.6.1 missing from Ruby Gems site

### ISSUE THREAD

**Issue by JohnAlbin** [at-import/breakpoint#146]
I'm in the process of testing out a new libsass workflow, but I was updating my Ruby workflow and noticed that Breakpoint 2.6.1 hasn't been pushed to ruby gems. https://rubygems.org/gems/breakpoint

Since the gemspec file is still in the repo, I assume this was accidental.

**Comment by drkenneth** [comment]
I suspect this is in part due to a bug in `breakpoint.gemspec` used for building the gem via `gem build breakpoint.gemspec`.

the file references `README.markdown` and `CHANGELOG.markdown` instead of `README.md` and `CHANGELOG.md`, which causes the build to fail.

**Comment by JohnAlbin** [comment]
I'd really like to get this fixed ASAP. I've got an open-source code base that uses breakpoint and I'd like it to work for Ruby users or for node-sass users.

Unfortunately, Breakpoint 2.6.1 complains about using $breakpoint-* variables _every single time you use `breakpoint()`_, and Breakpoint 2.5 doesn't have `breakpoint-set()`, so there's no way to provide a single codebase that works for both.

**Comment by Snugug** [comment]
I'll roll a release after the holiday break

**Comment by metaskills** [comment]
Please release :)
