### ISSUE TITLE
Suggestion for docs: Specify $BREAKPOINTS is the global map used by new @include add-breakpoint syntax

### ISSUE THREAD

**Issue by fosterinteractive** [at-import/breakpoint#148]
Other folks might be accessing the map used by @include add-breakpoint in their mixins. I suggest documenting the map name is $BREAKPOINTS.

(or suggest a better way to access the $BREAKPOINTS map)

--- Background as to why this is needed ---
I use the @include respond-to() syntax which has changed in a recent update of breakpoint version which recently showed this warning: 

WARNING: In order to avoid variable namespace collisions, we have updated the way to add breakpoints for respond-to. Please change all instances of `$breakpoints: add-breakpoint()` to `@include add-breakpoint()`. The `add-breakpoint()` function will be deprecated in a future release.

I applied the change. This broke my custom mixin that loads in a typography map with font sizes & line heights at different breakpoints. This mixin calls @include breakpoint by the names defined in their values in $breakpoints map. Before the update it was easy to know the map name before as I defined is with $breakpoints: add-breakpoint(). Now this is getting depreciated, so I suggest documenting $BREAKPOINT is the map name.

(If you're curious, this is the responsive typography gist - http://sassmeister.com/gist/ce35e07f8458ffe056ce)

**Comment by JohnAlbin** [comment]
Agreed this is a problem. While avoiding variable namespace collisions is good, you shouldn't resort to obfuscation for this as it prevents any other module from integrating with your module.

As an alternative to documenting the hard coded $BREAKPOINTS map name, you could also provide a robust API that allows you to query or modify the map without using its name. Note that might require something very similar to map-get() but without the map name. That sounds a lot harder than just documenting the map name, but it's an option.

**Comment by Snugug** [comment]
Adding the alternative `map-get` will be what I do. 3rd party modules shouldn't be relying on internals, they should have an API to access things

**Comment by Snugug** [comment]
That commit adds `get-breakpoint` function that will either return the full `$BREAKPOINTS` or the specific value of a breakpoint if you pass a name in
