### ISSUE TITLE
bower install breakpoint-sass --save-dev next steps?

### ISSUE THREAD

**Issue by mkoller** [at-import/breakpoint#150]
After I ran `bower install breakpoint-sass --save-dev` it installed correctly in bower_components.
How do I reference it? Do I call it by 

` @import "bower_components/compass-breakpoint/stylesheets/breakpoint" `

in my main.scss file ?  Do I have to add the folder using Compass's add_import_path config option instead of the standard require? 

I am using https://github.com/yeoman/generator-gulp-webapp

**Comment by bewards** [comment]
If you're using Gulp or Grunt, you can add the <i>includePaths</i> setting:

        settings: {
            includePaths: ['bower_components/breakpoint-sass/stylesheets/']
        }

And then just use: @import "breakpoint" in your main app.scss file to use it in any partial.

**Comment by mkoller** [comment]
Thanks @bewards , this can be closed.
