### ISSUE TITLE
Not compatible with later versions of sass...

### ISSUE THREAD

**Issue by Preen** [at-import/breakpoint#151]
Bundler could not find compatible versions for gem "sass":
  In snapshot (Gemfile.lock):
    sass (3.4.19)

  In Gemfile:
    breakpoint (= 2.4.2) ruby depends on
      sass (~> 3.3.0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

**Comment by strarsis** [comment]
You may install the npm package instead and use 
https://github.com/strarsis/sass-include-paths (with gulp-ruby-sass).

**Comment by Snugug** [comment]
The [latest version of the gem](https://rubygems.org/gems/breakpoint) should work with any version of Sass >= 3.3 and < 4. That looks like it's a problem with your Gemfile.lock file.
