### ISSUE TITLE
Declare an eyeglass version

### ISSUE THREAD

**Issue by strarsis** [at-import/breakpoint#152]
I get this message when compiling with sass
````
The following modules did not declare an eyeglass version:
[...]
breakpoint
[...]
````

Thank you and
With best regards

**Comment by cienvaras** [comment]
That happens because eyeglass needs a declaration of the needed version in the `package.json`. I tried the following, and it works perfectly to me:

```
"eyeglass": {
  "exports": "eyeglass-exports.js",
  "name": "breakpoint",
  "needs": "^0.7.0"
},
```

I can create a PR for that, however I'm not sure about the minimal supported version. Any ideas?

**Comment by strarsis** [comment]
I got answer in issue of eyeglass project:
(https://github.com/sass-eyeglass/eyeglass/issues/109#issuecomment-163991368)
````
The project is just using eyeglass to distribute sass files, the needs version can be *.
````

````
[...]
 "needs": "*"
[...]
````

With best regards

**Comment by cienvaras** [comment]
@strarsis Great, thanks for the feedback!

I created a PR for this here: https://github.com/at-import/breakpoint/pull/155
