### ISSUE TITLE
$breakpoint-no-query-fallbacks

### ISSUE THREAD

**Issue by gamsim** [at-import/breakpoint#158]
Hi Guys,

I want no query fallbacks but your documentation seems to be out of date now. Should I be setting these in the following way?

@include breakpoint-set('no query fallbacks', true);

And is there a way to specify a fallback class? Would this replace "true"?

@include breakpoint-set('no query fallbacks', '.lt-ie9');

**Comment by Snugug** [comment]
If you're using the latest _released_ version, the current documentation stands. We have not updated the documentation for the yet-unreleased updates moving to mixins
