### ISSUE TITLE
Problem with extend

### ISSUE THREAD

**Issue by kriss145** [at-import/breakpoint#159]
Hello

Do you have problem with using @extend on inside breakpoint function?
Maybe you have solution for that?

Example:

```
.item {
     @include breakpoint($breakpoint_tablet) {
          @extend %helper--clearfix;
     }
}
```

Result:

```
.item:after {
     clear: both;
     display: block;
}
```

Should be:

```
@media (max-width: 1225px) {
    .item:after {
        clear: both;
        display: block;
        content: '';
    }
}
```

**Comment by Snugug** [comment]
This is not possible to do in Sass. Please track https://github.com/sass/sass/issues/1050 for progress on Sass allowing this functionality.
