### ISSUE TITLE
Sass needs to be replaced as it is EoL

### ISSUE THREAD

**Issue by BKPepe** [at-import/breakpoint#185]
While installing breakpoint 2.7.1, I noticed that it installs sass. (https://github.com/at-import/breakpoint/blob/2.x.x/Gemfile#L4) and there is this deprecation warning:

```
Ruby Sass has reached end-of-life and should no longer be used.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  https://sass-lang.com/blog/ruby-sass-is-unsupported
```

**Comment by Snugug** [comment]
v3 was just released. I'm dropping support for Ruby Gems as Sass has moved over to the Node ecosystem. The latest version of Breakpoint fully supports Sass 1.25+
