### ISSUE TITLE
Remove compass dependency?

### ISSUE THREAD

**Issue by michaek** [at-import/breakpoint#92]
I see that Compass is not required for compiling breakpoint's CSS. https://github.com/Team-Sass/breakpoint/issues/46

Would it be acceptable to remove the gem dependency on Compass, using Compass::Frameworks.register if compass is available, falling back to Sass.load_paths? An example implementation is in bootstrap-sass: https://github.com/twbs/bootstrap-sass/blob/master/lib/bootstrap-sass.rb

**Comment by dkebler** [comment]
BTW Wiki still says depends on compass although according to bower.json only dependency is sassy-maps.  

Year+ later, so can now be used with npm Grunt Sass, libsass??

**Comment by Snugug** [comment]
Been able to for a while now, the Wiki is a bit out of date. Requires Libsass 3.2+

**Comment by dkebler** [comment]
I haven't loaded it yet.   So I can't use ruby gem sass 3.4.10? only
libsass?

On Fri, Feb 20, 2015 at 10:47 AM, Sam Richard <notifications@github.com>
wrote:

> Been able to for a while now, the Wiki is a bit out of date. Requires
> Libsass 3.2+
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/at-import/breakpoint/issues/92#issuecomment-75296267>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by Snugug** [comment]
Try loading it.
